name = "execu-ai-hub"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Pages 项目配置
pages_build_output_dir = "dist"
pages_build_command = "npm run build"

# 环境变量（本地开发用）
[vars]
NODE_ENV = "development"
NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY = "pk_live_Y2xlcmsuZ3B0LTUuY29tJA"
CLERK_SECRET_KEY = "sk_live_DR21PhOpwbArxoUJyxckCLlCHQEXZCwFP8GfaQNBDD"

# 生产环境配置
[env.production]
name = "execu-ai-hub-production"

[env.production.vars]
NODE_ENV = "production"
NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY = "pk_live_Y2xlcmsuZ3B0LTUuY29tJA"
CLERK_SECRET_KEY = "sk_live_DR21PhOpwbArxoUJyxckCLlCHQEXZCwFP8GfaQNBDD"

# 本地开发服务器配置
[dev]
port = 8787
local_protocol = "http"