name = "execu-ai-hub"
compatibility_date = "2024-01-01"

# Pages 项目配置
pages_build_output_dir = "dist"

# 环境变量（本地开发用）
[vars]
NODE_ENV = "development"

# 生产环境配置
[env.production]
name = "execu-ai-hub-production"

[env.production.vars]
NODE_ENV = "production"

# 本地开发服务器配置
[dev]
port = 8787
local_protocol = "http"

# 构建配置
[build]
command = "npm run build"

# 兼容性标志
compatibility_flags = ["nodejs_compat"]